name: identity_firebase
description: Firebase provider for Identity package
version: 0.2.0+1
author: Long Do <me@dotronglong.com>
homepage: https://github.com/dotronglong/dart-identity-firebase

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sso: ^0.2.0
  identity: ^0.2.0
  firebase_auth: ^0.15.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - images/firebase.png